version: 0.2

phases:
    install:
        commands:
            - /usr/local/bin/dotnet-install.sh --channel LTS
            
    build:
        commands:
            - sam build --base-dir ./src/mAPIonLambda/ --template ./src/mAPIonLambda/serverless.template 
            
    post_build:
        commands:
            - sam deploy --template-file ./.aws-sam/build/template.yaml --stack-name mapi-on-lambda --s3-bucket mapi-on-lambda-bucket --parameter-overrides BucketName=mapi-on-lambda-name --capabilities CAPABILITY_IAM
