version: 0.2

phases:
    install:
        commands:
            - /usr/local/bin/dotnet-install.sh --channel LTS
            - dotnet tool update -g Amazon.Lambda.Tools
            
    build:
        commands:
            #- sam build --base-dir ./src/mAPIonLambda/ --template ./src/mAPIonLambda/serverless.template 
            - cd src/mAPIonLambda/
            - dotnet lambda deploy-function mAPIonLambda --function-role MAPIonLAMBDA-role-v11pax7j --region eu-west-1 --function-runtime 6
            
    #post_build:
     #   commands:
      #      - sam deploy --template-file ./.aws-sam/build/template.yaml --stack-name mapi-on-lambda --s3-bucket mapi-on-lambda-bucket --parameter-overrides BucketName=mapi-on-lambda-name --capabilities CAPABILITY_IAM
